### ISSUE TITLE
time to switch into the next semester

### ISSUE THREAD

**Issue by Taskkillsqc** [vvbbnn00/USST-Lecture-Table-Calendar#5]
煮薄，我的学期选择呢

**Comment by vvbbnn00** [comment]
你好，Lecture Table的学期参数将在考试周结束后更新。

Hello, the semester parameter for Lecture Table will be updated after the end of the exam week.

**Comment by caodong0225** [comment]
哇，好厉害！

**Comment by 14790897** [comment]
好厉害
